const properties = [
    {
      id: 1,
      place: 'Ocean View Apartment',
      area: 1200,
      bedrooms: 2,
      bathrooms: 2,
      hospitalsNearby: 3,
      collegesNearby: 2,
    },
    {
      id: 2,
      place: 'Cozy Cottage',
      area: 800,
      bedrooms: 1,
      bathrooms: 1,
      hospitalsNearby: 1,
      collegesNearby: 0,
    },
    {
      id: 3,
      place: 'Modern Loft',
      area: 1500,
      bedrooms: 3,
      bathrooms: 2,
      hospitalsNearby: 2,
      collegesNearby: 3,
    },
    {
      id: 4,
      place: 'Riverside Villa',
      area: 2000,
      bedrooms: 4,
      bathrooms: 3,
      hospitalsNearby: 1,
      collegesNearby: 2,
    },
    {
      id: 5,
      place: 'Suburban Townhouse',
      area: 1800,
      bedrooms: 3,
      bathrooms: 2.5,
      hospitalsNearby: 2,
      collegesNearby: 1,
    },
    {
      id: 6,
      place: 'Urban Apartment',
      area: 1000,
      bedrooms: 2,
      bathrooms: 1.5,
      hospitalsNearby: 1,
      collegesNearby: 2,
    },
    {
      id: 7,
      place: 'Seaside Bungalow',
      area: 1400,
      bedrooms: 2,
      bathrooms: 2,
      hospitalsNearby: 2,
      collegesNearby: 1,
    },
    {
      id: 8,
      place: 'Mountain Retreat',
      area: 1600,
      bedrooms: 3,
      bathrooms: 2,
      hospitalsNearby: 0,
      collegesNearby: 1,
    },
    {
      id: 9,
      place: 'Downtown Loft',
      area: 1100,
      bedrooms: 1,
      bathrooms: 1,
      hospitalsNearby: 2,
      collegesNearby: 3,
    },
    {
      id: 10,
      place: 'Lakeside Cabin',
      area: 900,
      bedrooms: 2,
      bathrooms: 1,
      hospitalsNearby: 1,
      collegesNearby: 0,
    },
  ];
  
  export default properties;
  